"""Pure game-domain primitives for Kiba."""

from kiba_api.game.arithmetic import (
    TableArithmeticSummary,
    cards_have_same_rank,
    find_exact_value_subsets,
    get_arithmetic_mean,
    matches_exact_value,
    summarize_table_arithmetic,
)
from kiba_api.game.attack import (
    InitialAttackAnalysis,
    InitialAttackReason,
    analyze_initial_attack,
    is_legal_initial_attack,
)
from kiba_api.game.bout import (
    AttackPacket,
    BoutActionError,
    BoutErrorCode,
    BoutOutcome,
    BoutPhase,
    BoutState,
    Seat,
    finish_bout,
    play_defense,
    play_initial_attack,
    play_throw_in,
    play_transfer,
    take,
)
from kiba_api.game.cards import Card, JokerColor, Rank, Suit, TrumpState
from kiba_api.game.game import (
    GameActionError,
    GameErrorCode,
    GameOutcome,
    GamePhase,
    GameResult,
    GameState,
    create_36_card_deck,
    finish_game_bout,
    play_game_defense,
    play_game_initial_attack,
    play_game_throw_in,
    play_game_transfer,
    start_game_bout,
    take_game_bout,
)
from kiba_api.game.moves import (
    ThrowInAnalysis,
    ThrowInReason,
    ThrowInTargets,
    analyze_throw_in,
    get_throw_in_targets,
    is_legal_defense,
)
from kiba_api.game.scoring import (
    get_base_value,
    get_cards_value,
    get_effective_value,
    is_trump,
)
from kiba_api.game.transfer import TransferAnalysis, analyze_transfer

__all__ = [
    "AttackPacket",
    "BoutActionError",
    "BoutErrorCode",
    "BoutOutcome",
    "BoutPhase",
    "BoutState",
    "Card",
    "GameActionError",
    "GameErrorCode",
    "GameOutcome",
    "GamePhase",
    "GameResult",
    "GameState",
    "InitialAttackAnalysis",
    "InitialAttackReason",
    "JokerColor",
    "Rank",
    "Seat",
    "Suit",
    "TableArithmeticSummary",
    "ThrowInAnalysis",
    "ThrowInReason",
    "ThrowInTargets",
    "TransferAnalysis",
    "TrumpState",
    "analyze_initial_attack",
    "analyze_transfer",
    "analyze_throw_in",
    "cards_have_same_rank",
    "create_36_card_deck",
    "find_exact_value_subsets",
    "finish_bout",
    "finish_game_bout",
    "get_arithmetic_mean",
    "get_base_value",
    "get_cards_value",
    "get_effective_value",
    "get_throw_in_targets",
    "is_legal_defense",
    "is_legal_initial_attack",
    "is_trump",
    "matches_exact_value",
    "play_defense",
    "play_game_defense",
    "play_game_initial_attack",
    "play_game_throw_in",
    "play_game_transfer",
    "play_initial_attack",
    "play_throw_in",
    "play_transfer",
    "summarize_table_arithmetic",
    "start_game_bout",
    "take",
    "take_game_bout",
]
