"""PostgreSQL persistence primitives for accounts and match history."""

from kiba_api.persistence.account_data import ACCOUNT_EXPORT_VERSION, AccountDataService
from kiba_api.persistence.cosmetics import (
    COSMETICS,
    DEFAULT_COSMETIC_LOADOUT,
    CosmeticCatalogueState,
    CosmeticCategory,
    CosmeticCode,
    CosmeticDefinition,
    CosmeticError,
    CosmeticErrorCode,
    CosmeticLoadout,
    CosmeticService,
    CosmeticState,
    CosmeticSyncResult,
    CosmeticUnlockType,
)
from kiba_api.persistence.database import Base, Database
from kiba_api.persistence.matches import (
    MatchHistoryService,
    MatchOutcome,
    MatchStatistics,
    OpponentType,
)
from kiba_api.persistence.models import (
    AccountToken,
    AuthSession,
    CompletedMatch,
    User,
    UserAchievement,
    UserCosmeticLoadout,
    UserCosmeticUnlock,
    XPLedgerEntry,
)
from kiba_api.persistence.progression import (
    ACHIEVEMENTS,
    AchievementCode,
    AchievementDefinition,
    AchievementState,
    CosmeticAward,
    ProgressionAward,
    ProgressionService,
    ProgressionSummary,
    level_from_total_xp,
    progression_from_total_xp,
    xp_threshold_for_level,
)

__all__ = [
    "ACCOUNT_EXPORT_VERSION",
    "AccountDataService",
    "AuthSession",
    "Base",
    "CompletedMatch",
    "Database",
    "ACHIEVEMENTS",
    "AchievementCode",
    "AccountToken",
    "AchievementDefinition",
    "AchievementState",
    "COSMETICS",
    "DEFAULT_COSMETIC_LOADOUT",
    "CosmeticAward",
    "CosmeticCatalogueState",
    "CosmeticCategory",
    "CosmeticCode",
    "CosmeticDefinition",
    "CosmeticError",
    "CosmeticErrorCode",
    "CosmeticLoadout",
    "CosmeticService",
    "CosmeticState",
    "CosmeticSyncResult",
    "CosmeticUnlockType",
    "MatchHistoryService",
    "MatchOutcome",
    "MatchStatistics",
    "OpponentType",
    "ProgressionAward",
    "ProgressionService",
    "ProgressionSummary",
    "User",
    "UserAchievement",
    "UserCosmeticLoadout",
    "UserCosmeticUnlock",
    "XPLedgerEntry",
    "level_from_total_xp",
    "progression_from_total_xp",
    "xp_threshold_for_level",
]
